[workspace]
resolver = "2"
members = [
    "version-helper",
    "burn"
]
default-members = [
    "version-helper",
    "burn"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
repository = "https://github.com/vesuvisian/gst_yolov9"
rust-version = "1.88.0"

[workspace.dependencies]
gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", branch = "main" }
gst-base = { package = "gstreamer-base", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", branch = "main" }
gst-check = { package = "gstreamer-check", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", branch = "main" }
gst-plugin-version-helper = { path = "./version-helper" }
gst-video = { package = "gstreamer-video", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", branch = "main" }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
