[package]
name = "gst-burn"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "GStreamer Plugin for performing inference using Burn"
repository.workspace = true

[dependencies]
burn = { version = "0.22.0-pre.4", features = ["metal", "flex", "store"] }
bytemuck = "1.23.2"
fast_image_resize = { version = "5.3.0", features = ["image", "rayon"] }
gst = { workspace = true, features = ["serde"] }
gst-base.workspace = true
gst-video.workspace = true
image = { version = "0.25.8" }
imageproc = "0.25"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[dev-dependencies]
gst-check.workspace = true

[features]
static = []
capi = []

[lib]
name = "gstburn"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
